### ISSUE TITLE
[Design]_Lỗi ở trang chủ khi hiển thị nội dung bài post

### ISSUE THREAD

**Issue by HuyenPTSE03416** [sangnvus/201609JS02#10]
Khi hiển thị nội dung bài post thì khung của bài post dài ra khiến cho tất cả phần bên phải (xu hướng sách hiện nay, ...) bị đẩy xuống dưới.  [Xem ảnh đính kèm]
![bug design_trangchu](https://cloud.githubusercontent.com/assets/21986070/20035893/1c3bfb06-a429-11e6-8295-ce301ba29b38.JPG)

**Comment by HaiCMSE03143** [comment]
đã nhận issue :<
