### ISSUE TITLE
Comment for Dababase Designing

### ISSUE THREAD

**Issue by HuyenPTSE03416** [sangnvus/201609JS02#3]
- Notification: có cần senderId ko? (confuse -> update khi thực hiện demo)
- Conversation: Status của Message để kiểu boolean ko đủ để lưu trữ (confuse -> update khi thực hiện demo)
- Post: 
    >> có cần author tag ko?  (nhóm vote bỏ)
    >> comment: bỏ url
- Book: thống nhất hiểu rating point là tổng điểm rating cộng dồn (chứ ko phải avg)
- Report: 
  >> bỏ groupId
  >> status đổi kiểu (update khi thực hiện demo)
- Group:
  >> bỏ url 
  >> GroupMember: thiếu role (Initiator, Admin, Member)
  >> Phần tag của group: sách/tác giả

**Comment by VanTTCSE03409** [comment]
updated all comment by v1.1
Link : https://github.com/sangnvus/201609JS02/blob/master/WIP/Users/VanTTC/BSN_MongoDB_Database_Design_v1.1.xlsx
