### ISSUE TITLE
Comment về giao diện trang quản lý Slider

### ISSUE THREAD

**Issue by HuyenPTSE03416** [sangnvus/201609JS02#5]
**Hiện tượng:** Click vào button "Thêm Slide" thì khung Pop-up bị đẩy phần lớn ra ngoài màn hình => Không thao tác được. _<Xem ảnh đính kèm>_

**Dự đoán nguyên nhân:** Do  .modal-dialog có thuộc tính **left: 50%**  (khi tớ đặt về auto thì hiển thị bình thường).   _<Xem ảnh đính kèm>_

Nhờ team design xem lại phần này nhé ^.^

![hi n t ng l i](https://cloud.githubusercontent.com/assets/21986070/19798535/da24f362-9d1b-11e6-8c0c-a6b3d134cc3c.png)
![nguyen nhan gay l i](https://cloud.githubusercontent.com/assets/21986070/19798536/da25c26a-9d1b-11e6-8857-8ff3fb4504ba.JPG)

**Comment by HaiCMSE03143** [comment]
đã xử lí
